webtalk_init -webtalk_dir /home/hfl/ldata/vivado/project_1/project_1.sim/sim_1/behav/xsim/xsim.dir/adder_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Jan  3 20:29:31 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2021.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3247384" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "a3119a6e-b25a-470e-aae6-9d852755f91e" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "c483afc7452446038085ecf7b0091341" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "38" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "unknown" -context "user_environment"
webtalk_add_data -client project -key os_release -value "unknown" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 7 4800H with Radeon Graphics" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2900.000 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "33.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "3" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.05_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "124736_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1549712783 -regid "" -xml /home/hfl/ldata/vivado/project_1/project_1.sim/sim_1/behav/xsim/xsim.dir/adder_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/hfl/ldata/vivado/project_1/project_1.sim/sim_1/behav/xsim/xsim.dir/adder_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/hfl/ldata/vivado/project_1/project_1.sim/sim_1/behav/xsim/xsim.dir/adder_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
