#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2021.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Mon Jan 03 10:46:23 CST 2022
# SW Build 3247384 on Thu Jun 10 19:36:07 MDT 2021
#
# IP Build 3246043 on Fri Jun 11 00:30:35 MDT 2021
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab -wto c483afc7452446038085ecf7b0091341 --incr --debug typical --relax --mt 8 -L work -L secureip --snapshot adder_tb_behav work.adder_tb -log elaborate.log"
xelab -wto c483afc7452446038085ecf7b0091341 --incr --debug typical --relax --mt 8 -L work -L secureip --snapshot adder_tb_behav work.adder_tb -log elaborate.log

